### ISSUE TITLE
Make the throttling timeout configurable

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-autosave#10]
I'm afraid that the current 500ms is too fast for most integrations.

**Comment by Reinmar** [comment]
I [changed it to 1000ms](https://github.com/ckeditor/ckeditor5-autosave/commit/d7854196375c2ba57e5affd81071b01a7cad6d77) because it created too much noise even for the sample.

Still, it should be configurable. But we should perhaps think on https://github.com/ckeditor/ckeditor5-autosave/issues/12 first.

**Comment by pjasiun** [comment]
After https://github.com/ckeditor/ckeditor5-autosave/issues/12#issuecomment-408116612 default timeout should work in most cases and is should not need to be configurable.
