### ISSUE TITLE
No saving in case of loosing internet connection

### ISSUE THREAD

**Issue by mauschepano** [ckeditor/ckeditor5-autosave#21]
If the user isn't connected to the internet from time to time while editing, the autosave function doesn't work. 
In this case you will get the alert message "Are you sure to leave the website..." (or something like that) but you have no chance to save the data with the autosave function.
Or did i miss something?

**Comment by pjasiun** [comment]
The way how data will be saved to the server is up to the provided adapter. All, what autosave plugin do is to execute your callback function whenever your data need to be saved: whenever data change. It also set pending action to notify the user that there are not saved data if he wants to try to close the editor. However, this plugin does nothing with the internet connection, it might be even not needed. For instance, one may use this plugin to save data to the local storage. 

So feel free to create an adapter which will check the internet connection and handle the connection lost.
