### ISSUE TITLE
Docs for `autosave.waitingTime` are missing

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-autosave#24]
There should be a configuration option to define how often the save action should occur. Now it is 5 seconds after the editing action ends and it might be too often depending on the solution.

**Comment by ma2ciek** [comment]
Now this time defaults to 1s and is configurable via `autosave.waitingTime`. See https://github.com/ckeditor/ckeditor5-autosave/blob/4fe9599d6bcf204669bccd2973a5d732eb129e5a/src/autosave.js#L71-L73, https://github.com/ckeditor/ckeditor5-autosave/blob/4fe9599d6bcf204669bccd2973a5d732eb129e5a/src/autosave.js#L344-L360

**Comment by ma2ciek** [comment]
Not sure why but these docs don't render from https://ckeditor.com/docs/ckeditor5/latest/api/module_autosave_autosave-AutosaveConfig.html.

And this property should be mentioned also here: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/saving-data.html#autosave-feature
