### ISSUE TITLE
Listen to change:data event with low priority 

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-autosave#4]
In the meantime, there could be some conversion callbacks executed along with fired listeners for the `document#change` that might change the data model.

**Comment by pjasiun** [comment]
I disagree. Users should be able to use `change:data` event easily. They should not need to know about any priorities. This is not an internal event, but the one designed for developers who integrates the editor. It should be as simple to use as possible. If we will have more problems like this in the future we may consider adding high priority to the conversion.

**Comment by pjasiun** [comment]
Also, we may consider better protection in `view.render`. It is not a first case where some methods, which supposes not to, call `render`.
